name: app_tournament
description: A new Flutter project.

publish_to: 'none'

version: 1.0.2+3

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1
  clipboard: ^0.1.3
  cloud_firestore: ^4.3.0
  country_picker: ^2.0.14
  crypto: ^3.0.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.2.3
  firebase_core: ^2.4.0
  firebase_messaging: ^14.2.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_faq: ^1.0.1+1
  flutter_feather_icons: ^2.0.0+1
  flutter_local_notifications: ^13.0.0
  flutter_svg: ^1.0.3
  flutter_svprogresshud: ^1.0.0
  flutter_web_browser: ^0.17.1
  flutterwave_payment: ^0.0.4+2
  flutterwave_standard: ^1.0.6
  font_awesome_flutter: ^10.3.0
  google_fonts: ^3.0.1
  google_sign_in: ^5.2.4
  hive: ^2.0.5
  http: ^0.13.5
  ionicons: ^0.2.1
  json_annotation: ^4.4.0
  lottie: ^2.2.0
  path_provider: ^2.0.9
  provider: ^6.0.2
  razorpay_flutter: ^1.2.9
  rxdart: ^0.27.3
  shimmer: ^2.0.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4

flutter:

  uses-material-design: true

  assets:
    - assets/
    - .env
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
